import React,{useState} from 'react';
import {calculateScenario} from '../model/design.mjs';
import {stopGeometry,TAU} from '../model/journeys.mjs';
const study=calculateScenario();
const fmt=(n:number,d=1)=>n.toLocaleString(undefined,{maximumFractionDigits:d});
export function StopContinuity(){
 const [ring,setRing]=useState(7),[phase,setPhase]=useState(17),[stations,setStations]=useState(64),[reach,setReach]=useState(30),[outage,setOutage]=useState(4),[reserve,setReserve]=useState(50);
 const geo=study.rings[ring],sys=study.ringSystems[ring];
 const m=stopGeometry({radius:geo.outerRadius+4,phaseDegrees:phase,exits:sys.moduleCount,fixedStations:stations,hydrantSpacing:50,hoseReach:reach,radialGap:4});
 const waterHours=12*reserve/100/1.5,wasteHours=6*reserve/100/2.5;
 return <div className="stop-study">
 <div className="callout"><p><strong>Arbitrary-angle continuity is not yet proven.</strong> A continuous fixed landing gallery removes the need to line an exit up with a discrete bridge. The calculations below establish geometric bounds only. Structural clearance, smoke protection, accessible escape and connections still need professional design and full-scale tests.</p></div>
 <div className="systems-lab"><div className="lab-heading"><div><p className="eyebrow">STOP AT ANY ANGLE</p><h3>Test the alignment dependency</h3></div><span className="tag">Geometry, not evacuation certification</span></div>
 <div className="ring-picker">{study.rings.map((_:any,i:number)=><button key={i} aria-pressed={ring===i} onClick={()=>setRing(i)}>R{i+1}</button>)}</div>
 <div className="assumption-controls lab-controls">
 <label>Stop angle <output>{phase}°</output><input type="range" min="0" max="360" value={phase} onChange={e=>setPhase(+e.target.value)}/></label>
 <label>Fixed exits from gallery <output>{stations}</output><input type="range" min="16" max="256" step="16" value={stations} onChange={e=>setStations(+e.target.value)}/></label>
 <label>Usable emergency hose reach <output>{reach} m</output><input type="range" min="10" max="60" value={reach} onChange={e=>setReach(+e.target.value)}/></label>
 </div>
 <div className="stop-geometry"><svg viewBox="0 0 440 440" role="img" aria-label="Moving module exits at chosen stop angle face a continuous stationary gallery. Fixed escape nodes are distributed around that gallery.">
 <circle cx="220" cy="220" r="170" fill="none" stroke="var(--accent)" strokeWidth="14"/><circle cx="220" cy="220" r="143" fill="none" stroke="var(--ring)" strokeWidth="22"/>
 {m.exitAngles.map((a:number,i:number)=><circle key={`e${i}`} cx={220+143*Math.cos(a)} cy={220+143*Math.sin(a)} r="2.7" fill="var(--text)"/>)}
 {Array.from({length:stations},(_,i)=>{const a=TAU*i/stations;return <path key={i} d={`M${220+170*Math.cos(a)} ${220+170*Math.sin(a)}L${220+192*Math.cos(a)} ${220+192*Math.sin(a)}`} stroke="#65c8d0" strokeWidth="3"/>})}
 <text x="220" y="200" textAnchor="middle" fill="var(--text)" fontSize="23">Ring {ring+1} · stopped</text><text x="220" y="232" textAnchor="middle" fill="var(--muted)" fontSize="15">{phase}° phase</text><text x="220" y="263" textAnchor="middle" fill="var(--muted)" fontSize="14">Clearances exaggerated</text>
 </svg><div><p><strong>White:</strong> module exits. <strong>Amber:</strong> continuous fixed gallery. <strong>Blue:</strong> exits to independent fixed routes.</p><div className="result-grid compact-results"><div><strong>{fmt(m.worstWalk)} m</strong><span>Longest gallery leg at this phase*</span></div><div><strong>{fmt(m.allAngleBound)} m</strong><span>Upper bound at ANY phase*</span></div><div><strong>{m.hoseMargin>=0?'Y':'N'}</strong><span>Geometric hose reach covered</span></div></div><p className="caption">*To the nearest fixed node, assuming both directions remain available. Not distance to safety or total evacuation time. If the nearest node is unavailable, the maximum with one isolated failed node becomes one full node pitch: {fmt(2*m.allAngleBound)} m. A blocked gallery sector needs a separate route.</p></div></div>
 <details><summary>What the all-angle calculation actually proves</summary><p>For equally spaced fixed nodes, the farthest point along an unobstructed circular gallery is half a node pitch from a node: πR/N. This bound holds for every stop angle, not just sampled positions. A continuous landing edge provides a geometric receiving surface opposite every module exit. It does not establish a usable threshold, adequate width, structural capacity or smoke tenability.</p><p>Emergency service outlets every 50 m require up to 25 m along the gallery plus the assumed 4 m radial crossing: 29 m of routed hose. Your {reach} m reach gives {fmt(m.hoseMargin)} m margin before bends and slack. Pressure, bend radius, compatible connectors, crew deployment and sanitary requirements are additional. Outlet spacing is a new study assumption, not the normal six/eight carriage stations. On this gallery it implies at least {Math.ceil(TAU*(geo.outerRadius+4)/50)} outlets per service network, with separate potable and wastewater equipment. That scale needs a cost and maintenance assessment.</p></details>
 </div>
 <div className="two-column"><article className="brief-card"><h3>1. Secure motion; preserve refuge</h3><p>Detect the fault, isolate hazardous equipment, apply independently controlled brakes and verify zero speed with redundant sensing. Emergency energy keeps alarms, lighting, controls and required essential loads available. Do not release a bridge simply because the drive command says “stop.”</p></article><article className="brief-card"><h3>2. Deploy onto the fixed gallery</h3><p>After motion is restrained, short module-side threshold bridges reach the independent gallery. Fixed routes connect galleries to stairs, protected crossings and ultimate discharge. Cross-ring spines must clear the entire moving building envelope—for example above roof level with independent supports in fixed gaps. A fixed bridge cannot simply pass through occupied rotating buildings. Buildings still need internal protected egress and an accessible evacuation strategy; a ground-level gallery cannot evacuate upper floors by itself.</p></article></div>
 <div className="systems-lab"><h3>Will the reserve last until service is restored?</h3><div className="assumption-controls lab-controls"><label>Restoration delay <output>{outage} h</output><input type="range" min="0" max="12" step=".5" value={outage} onChange={e=>setOutage(+e.target.value)}/></label><label>Usable reserve / spare tank volume <output>{reserve}%</output><input type="range" min="10" max="100" step="5" value={reserve} onChange={e=>setReserve(+e.target.value)}/></label></div>
 <div className="table-scroll"><table className="technical-table"><thead><tr><th>Service</th><th>Available endurance</th><th>Covers delay?</th><th>Stopped-ring strategy</th></tr></thead><tbody>
 <tr><td>Fresh water</td><td>{fmt(waterHours)} h at 1.5× demand</td><td>{outage<=waterHours?'Y':'N'}</td><td>Usable ring tanks → separate sanitary emergency outlets; temporary approved connections after isolation</td></tr>
 <tr><td>Wastewater</td><td>{fmt(wasteHours)} h at 2.5× inflow</td><td>{outage<=wasteHours?'Y':'N'}</td><td>Spare sealed tank volume → separate solids-rated emergency pumping points; no open discharge</td></tr>
 <tr><td>Essential power</td><td>Not sized</td><td>Unknown</td><td>Independent stored energy / backup; segmented collectors must maintain contact while stopped</td></tr>
 <tr><td>Fire water</td><td>Not sized</td><td>Unknown</td><td>Dedicated storage and pumps, separate from domestic reserve</td></tr>
 </tbody></table></div><p>Ring {ring+1}: nominal domestic tank {fmt(sys.waterBufferM3/1000)} ML; nominal wastewater buffer {fmt(sys.ringWastewaterM3Day/4/1000)} ML. Only {reserve}% is credited here. Catch-up pumping after restoration must exceed continuing inflow. None of these service durations represents safe evacuation time.</p></div>
 <div className="table-scroll"><table className="technical-table"><thead><tr><th>Failure case</th><th>Requirement</th><th>Evidence still needed</th></tr></thead><tbody>
 <tr><td>Stop between normal ports</td><td>Continuous gallery; reachable independent service outlets</td><td>Full circumference access, hose routing, manifold capacity and deployment time</td></tr>
 <tr><td>One threshold fails</td><td>Independent alternative module exit</td><td>Two-route internal access, travel limits and accessibility</td></tr>
 <tr><td>Smoke / fire blocks gallery</td><td>Separated refuge and alternative fixed discharge</td><td>Tenability, compartmentation, capacity and fire analysis</td></tr>
 <tr><td>Seismic misalignment</td><td>Crossings tolerate defined displacement or remain closed</td><td>Movement envelope and refuge survival when deployment is impossible</td></tr>
 <tr><td>Common power loss</td><td>Independent restraint, essential loads and alarms</td><td>Black-start, reserve capacity and end-to-end failure testing</td></tr>
 </tbody></table></div>
 <p className="caption">Design references: <a href="https://www.access-board.gov/ada/guides/chapter-4-accessible-routes/">US Access Board · accessible routes</a>; <a href="https://www.nist.gov/programs-projects/safety-building-occupants-project">NIST · evacuation behavior and movement</a>; <a href="https://www.epa.gov/waterutilityresponse">EPA · utility emergency response</a>. These guide the test program; they do not approve this mechanism.</p>
 </div>;
}
