import React,{useState,useMemo,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {destinations,home,journey,position,TAU} from '../model/journeys.mjs';
import {ringGeometry} from '../model/design.mjs';
import {BoardingStudy} from '../components/BoardingStudy';
const rings=ringGeometry();
const num=(v:number)=>v.toLocaleString(undefined,{maximumFractionDigits:1});
const clock=(h:number)=>`${String(Math.floor(h)%24).padStart(2,'0')}:${String(Math.round(h%1*60)).padStart(2,'0')}`;
export default function JourneysPage(){
 const [hour,setHour]=useState(0),[walking,setWalking]=useState(1.3),[selected,setSelected]=useState(5),[playing,setPlaying]=useState(false),[comparison,setComparison]=useState('midnight'),[sort,setSort]=useState('name'),[ascending,setAscending]=useState(true),[category,setCategory]=useState('All'),[delay,setDelay]=useState(0);
 useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setHour(h=>(h+.25)%24),500);return()=>clearInterval(timer)},[playing]);
 const options={departureHours:hour,walking,stations:32,boardingSeconds:delay};
 const rows=useMemo(()=>destinations.map(d=>{const moving=journey(d,options),fixed=journey(d,{...options,speed:0,freezeAtHours:comparison==='now'?hour:0});return {...d,moving,fixed,saved:(fixed.seconds-moving.seconds)/60}}),[hour,walking,delay,comparison]);
 const filtered=rows.filter(d=>category==='All'||d.category===category).sort((a,b)=>{const v=sort==='name'?a.name.localeCompare(b.name):sort==='ring'?a.ring-b.ring:sort==='moving'?a.moving.seconds-b.moving.seconds:sort==='fixed'?a.fixed.seconds-b.fixed.seconds:a.saved-b.saved;return ascending?v:-v});
 const item=rows.find(d=>d.id===selected)!;
 const day=useMemo(()=>Array.from({length:97},(_,i)=>{const h=i/4;return {h,m:journey(item,{...options,departureHours:h}).seconds/60,f:journey(item,{...options,departureHours:h,speed:0,freezeAtHours:comparison==='now'?h:0}).seconds/60}}),[selected,walking,delay,comparison]);
 const best=day.slice(0,-1).reduce((a,b)=>a.m<b.m?a:b),worst=day.slice(0,-1).reduce((a,b)=>a.m>b.m?a:b);
 const top=Math.ceil(Math.max(...day.flatMap(d=>[d.m,d.f]))/10)*10||10;
 const graph=(key:'m'|'f')=>day.map((d,i)=>`${i?'L':'M'}${50+d.h/24*620},${240-d[key]/top*190}`).join(' ');
 const point=(ring:number,angle:number)=>[230+rings[ring].midRadius/4100*190*Math.cos(angle),230+rings[ring].midRadius/4100*190*Math.sin(angle)];
 const hp=point(home.ring,position(home,hour*3600)),dp=point(item.ring,position(item,hour*3600));
 const sorting=(key:string)=>{if(sort===key)setAscending(!ascending);else{setSort(key);setAscending(true)}};
 return <main id="main-content"><header className="page-header"><p className="eyebrow">ROTUNDA / DAILY JOURNEYS</p><h1>When does your<br/><em>destination come closer?</em></h1><p>Thirty everyday destinations, including four restaurants. Compare departure times and walking routes as the rings turn. These are illustrative locations—not a finalized land-use plan.</p></header>
 <section className="section technical-section"><div className="callout"><p><strong>Conditional route model.</strong> Assumes 32 fixed, grade-separated radial spines and direct-step boarding interfaces available at every departure. Their engineering and capacity are not demonstrated. Results exclude queues, building interiors and vertical travel; they are not evacuation times.</p></div>
 <div className="journey-controls systems-lab"><div className="assumption-controls"><label>Departure <output>{clock(hour)}</output><input type="range" min="0" max="23.75" step=".25" value={hour} onChange={e=>{setPlaying(false);setHour(+e.target.value)}}/></label><label>Walking speed <output>{walking.toFixed(1)} m/s</output><input type="range" min=".6" max="1.8" step=".1" value={walking} onChange={e=>setWalking(+e.target.value)}/></label><label>Optional access allowance / boundary <output>{delay} s</output><input type="range" min="0" max="300" step="15" value={delay} onChange={e=>setDelay(+e.target.value)}/></label></div>
 <div className="journey-actions"><button className="button secondary" aria-pressed={playing} onClick={()=>setPlaying(!playing)}>{playing?'Pause day':'Play day · 1800×'}</button><label>Stationary comparison <select value={comparison} onChange={e=>setComparison(e.target.value)}><option value="midnight">Fixed city at 00:00 layout</option><option value="now">Freeze current layout</option></select></label></div></div>
 <div className="journey-feature"><div><p className="eyebrow">SELECTED DESTINATION</p><h2>{item.name}</h2><p>Home on Ring 2 → Ring {item.ring+1}. {item.ring===home.ring?'Same-ring separation stays constant. Rotation does not shorten this direct local walk.':'Other rings change phase relative to home. A closer angular position does not remove the radial walking distance.'}</p>
 <div className="result-grid compact-results"><div><strong>{num(item.moving.seconds/60)} min</strong><span>Rotating · leave {clock(hour)}</span></div><div><strong>{num(item.fixed.seconds/60)} min</strong><span>Stationary comparison</span></div><div><strong>{num(Math.abs(item.saved))} min</strong><span>{Math.abs(item.saved)<.05?'No change':item.saved>0?'Faster with rotation':'Slower with rotation'}</span></div></div>
 <p className="caption">Rotating route: {num(item.moving.walkMeters/1000)} km walked. {item.moving.station<0?'Direct walk on home ring.':`Fixed spine ${item.moving.station+1}: ${num(item.moving.first/60)} min to spine + ${num(item.moving.radial/60)} min radial walk + ${num(item.moving.last/60)} min on destination ring + ${num(item.moving.boarding/60)} min transfers.`}</p></div>
 <svg viewBox="0 0 460 460" role="img" aria-label={`City positions at ${clock(hour)}. Home on Ring 2 in cyan; ${item.name} on Ring ${item.ring+1} in amber. Positions only, not a route line.`}>
 {rings.map((r:any,i:number)=><circle key={i} cx="230" cy="230" r={r.midRadius/4100*190} fill="none" stroke={i===item.ring?'var(--accent)':'var(--line)'} strokeWidth={i===item.ring?8:5}/>)}
 {Array.from({length:32},(_,i)=><path key={i} d={`M${230+800/4100*190*Math.cos(TAU*i/32)} ${230+800/4100*190*Math.sin(TAU*i/32)}L${230+190*Math.cos(TAU*i/32)} ${230+190*Math.sin(TAU*i/32)}`} stroke="var(--line)" opacity=".5"/>)}
 <circle cx={hp[0]} cy={hp[1]} r="7" fill="#65c8d0" stroke="var(--bg)" strokeWidth="2"/><circle cx={dp[0]} cy={dp[1]} r="7" fill="var(--accent)" stroke="var(--bg)" strokeWidth="2"/>
 <text x="20" y="25" fill="#65c8d0" fontSize="14">● Home · R2</text><text x="20" y="448" fill="var(--accent)" fontSize="14">● Destination · R{item.ring+1} · {clock(hour)}</text>
 </svg></div>
 <div className="systems-lab"><h3>{item.name}: walking time through the day</h3><p>Amber = rotating. Cyan dashed = stationary comparison. Use the departure slider or the best-departure button to inspect the route.</p><svg className="journey-chart" viewBox="0 0 720 290" role="img" aria-label={`Walking times sampled every 15 minutes. Best rotating time ${num(best.m)} minutes at ${clock(best.h)}, worst ${num(worst.m)} minutes at ${clock(worst.h)}.`}>
 {[0,.5,1].map(f=><g key={f}><path d={`M50 ${240-f*190}H670`} stroke="var(--line)"/><text x="42" y={245-f*190} textAnchor="end" fill="var(--muted)" fontSize="14">{num(top*f)}</text></g>)}
 {[0,6,12,18,24].map(h=><text key={h} x={50+h/24*620} y="270" textAnchor="middle" fill="var(--muted)" fontSize="14">{String(h).padStart(2,'0')}:00</text>)}
 <path d={graph('f')} fill="none" stroke="#65c8d0" strokeDasharray="6 5" strokeWidth="2"/><path d={graph('m')} fill="none" stroke="var(--accent)" strokeWidth="3"/><path d={`M${50+hour/24*620} 35V240`} stroke="var(--text)" strokeDasharray="3 4"/><text x="50" y="23" fill="var(--muted)" fontSize="14">Minutes · 15-minute departure samples</text>
 </svg><p>Best sampled departure: <button className="text-button" onClick={()=>{setPlaying(false);setHour(best.h)}}>{clock(best.h)} · {num(best.m)} min</button>. Longest sampled trip: {num(worst.m)} min at {clock(worst.h)}. These are sample extrema, not an exact optimum. Ring periods differ, so tomorrow’s pattern need not repeat today’s.</p></div>
 <div className="section-heading"><div><p className="eyebrow">30 EVERYDAY EXAMPLES</p><h2>Compare the trips.</h2></div><label>Category <select value={category} onChange={e=>setCategory(e.target.value)}>{['All',...new Set(destinations.map(d=>d.category))].map(c=><option key={c}>{c}</option>)}</select></label></div>
 <p className="caption">Select a destination to update the map and chart. Click column headings to sort. Positive minutes saved means rotation helps.</p>
 <div className="table-scroll"><table className="technical-table journey-table"><thead><tr>{[['name','Destination'],['ring','Ring'],['moving','Rotating min'],['fixed','Fixed min'],['saved','Min saved']].map(([k,l])=><th key={k} aria-sort={sort===k?(ascending?'ascending':'descending'):'none'}><button onClick={()=>sorting(k)}>{l}{sort===k?(ascending?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{filtered.map(d=><tr key={d.id} className={selected===d.id?'selected-trip':''}><td><button aria-pressed={selected===d.id} onClick={()=>setSelected(d.id)}>{d.name}</button></td><td>{d.ring+1}</td><td>{num(d.moving.seconds/60)}</td><td>{num(d.fixed.seconds/60)}</td><td>{num(d.saved)}</td></tr>)}</tbody></table></div>
 <details className="handoff-detail"><summary>How the route calculation works</summary><p>Home begins at angle zero on Ring 2 at 00:00. Fixed spines must sit outside the full swept building envelope on independent structures; spans over the 300 m-wide rings and vertical access are not designed here. Each ring’s centerline travels at 0.5 m/s in alternating directions. For each of 32 fixed spines, solve the time to reach its stationary entrance while walking either way on the moving home ring. Add a fixed boundary allowance, walk the stationary radial spine, add the destination access allowance, then walk the shorter arc on that ring. The destination’s phase is calculated at boarding time, not departure time. Choose the fastest of these 32 immediate-departure routes.</p><p>Same-ring trips use the direct shorter arc. The model does not search routes that leave and re-enter that ring, voluntary waiting, multimodal transit, or intermediate-ring shortcuts. All destinations sit on centerlines; transfers from centerline to edge, bridge elevations and interior access are idealized. A “fixed city at 00:00” compares evolving locations with one frozen layout. “Freeze current layout” holds departure positions equal and isolates motion during the trip. Neither is a demand-weighted citywide transport-benefit estimate.</p><p>Walking speed and transfer delay are user assumptions. Longer travel times are intentional outputs: slow rotation does not make an 8.2 km city walkable by itself. Local distribution of essentials and fixed transit remain necessary.</p></details>
 <BoardingStudy/>
 <Link className="inline-link" to="/infrastructure#stopped">Inspect arbitrary-stop utilities and evacuation →</Link>
 </section></main>;
}
