import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Circle, MoveUpRight, Waves, Layers3, Cog } from 'lucide-react';
import Masterplan from '../components/Masterplan';
import { calculateScenario, gates } from '../model/design.mjs';

const design = calculateScenario();
export default function VisionPage() {
  return <main id="main-content" className="editorial">
    <section className="hero">
      <img className="hero-image" src={`${import.meta.env.BASE_URL}rotunda-concept.webp`} alt="Architectural concept impression of concentric inhabited city rings, green corridors and a central civic hub at dusk" width="1536" height="1024" fetchPriority="high" />
      <div className="hero-shade" />
      <div className="hero-content"><p className="eyebrow">ROTUNDA / A KINETIC CITY PROPOSAL</p><h1>A city with<br />a different<br /><em>turn of mind.</em></h1><p className="hero-intro">Eight inhabited rings. A fixed civic heart.<br />A new way to explore density, landscape and movement.</p><div className="hero-actions"><Link to="/explore" className="button primary">Explore the city <ArrowUpRight size={19} /></Link><a href="#vision" className="button glass">Discover the concept <ArrowRight size={18} /></a></div></div>
      <div className="hero-bottom"><span>01 / THE VISION</span><span>Revision 0.2 · concept impression · no site selected</span></div>
    </section>
    <div className="metric-strip"><div><strong>08</strong><span>Concentric rings</span></div><div><strong>{design.diameterKm.toFixed(1)}<small> km</small></strong><span>Concept diameter</span></div><div><strong>150<small> m</small></strong><span>Between ring edges</span></div><div><strong>15</strong><span>Floors per inhabited ring</span></div></div>
    <section id="vision" className="section intro-grid"><div><p className="eyebrow">ABOUT THE PROPOSAL</p><h2>What if the city<br />moved around you?</h2></div><div><p className="lead">Rotunda is a pre-feasibility study for a compact circular city in which inhabited neighborhoods move slowly around a stationary civic hub.</p><p>Homes, workplaces and shared spaces occupy articulated ring modules. Landscaped corridors, regional transit, emergency access and the major utility backbone remain fixed. Distributed guideways carry the rings; controlled ground stations transfer water, wastewater and power.</p><p>Rotation is the research question—not a proven benefit. It must outperform a well-designed static circular city in access, resilience, cost and quality of life before any full-scale commitment.</p><Link className="inline-link" to="/feasibility">See the development case <ArrowUpRight size={18}/></Link></div></section>
    <section className="section plan-section"><div className="plan-story"><p className="eyebrow">02 / THE MASTERPLAN</p><h2>A shared center.<br />An open horizon.</h2><p>A family of concentric neighborhoods creates a repeatable urban structure, with space between the rings for landscape, fixed circulation and service access.</p><div className="numbered-note"><span>01</span><div><h3>The civic heart</h3><p>A stationary hub for cultural, public and interchange uses.</p></div></div><div className="numbered-note"><span>02</span><div><h3>The inhabited rings</h3><p>300 m planning bands, subdivided by courtyards, daylight corridors and building clusters.</p></div></div><div className="numbered-note"><span>03</span><div><h3>The fixed network</h3><p>Regional transit and emergency services remain independent of whether the rings are moving.</p></div></div></div><Masterplan /></section>
    <section className="section"><div className="section-heading"><div><p className="eyebrow">03 / LIFE BETWEEN THE RINGS</p><h2>Density with room to live.</h2></div><span className="caption">Design intentions to test in a site-specific masterplan</span></div><div className="principles"><article><Layers3 /><span>01</span><h3>Mixed-use neighborhoods</h3><p>Put daily needs within each ring. Design schools, healthcare, work and public space around actual walking routes.</p></article><article><Circle /><span>02</span><h3>Landscape as infrastructure</h3><p>Use the fixed gaps for shade, ecology, service galleries and stormwater systems appropriate to the host climate.</p></article><article><MoveUpRight /><span>03</span><h3>Connections that endure</h3><p>Provide protected, accessible transfers and fixed transit. Treat emergency evacuation as a primary design driver.</p></article></div></section>
    <section className="section system-story"><div className="section-heading"><div><p className="eyebrow">04 / THE OPERATING IDEA</p><h2>Move the districts.<br/>Keep the lifelines fixed.</h2></div><Link className="inline-link" to="/infrastructure#motion">See the mechanism <ArrowUpRight size={18}/></Link></div><div className="system-story-grid"><article><Cog/><span>01</span><h3>Articulated ring modules</h3><p>Approximately 200 m structural modules ride on redundant bogies and multiple circular rail bands. Distributed drives and brakes localize faults.</p></article><article><Waves/><span>02</span><h3>Ground-fed water</h3><p>Fixed loop mains serve multiple synchronized transfer carriages. Sealed couplers fill protected ring-side tanks; water is not poured from above.</p></article><article><MoveUpRight/><span>03</span><h3>Buffered waste transfer</h3><p>Sector sumps feed holding tanks. Separate traveling carriages transfer sewage to the fixed sewer with isolation and missed-transfer capacity.</p></article></div><p className="caption system-disclaimer">This is a selected engineering hypothesis for comparison and testing. It is not a construction-ready mechanism.</p></section>
    <section className="utility-feature section"><div><p className="eyebrow">05 / WHAT MAKES IT POSSIBLE</p><h2>Below the vision,<br /><em>the vital systems.</em></h2><p>Water in. Waste out. Power and people across a moving boundary. The infrastructure study now traces each load path, operating state and utility transfer—and identifies what a demonstrator must prove.</p><Link className="button primary" to="/infrastructure">Inside the infrastructure <ArrowUpRight size={18}/></Link></div><div className="utility-index"><Link to="/infrastructure#motion"><span>01</span><h3>Ground and rotation</h3><ArrowUpRight/></Link><Link to="/infrastructure#water"><span>02</span><h3>Ground-fed freshwater</h3><ArrowUpRight/></Link><Link to="/infrastructure#sewage"><span>03</span><h3>Buffered wastewater</h3><ArrowUpRight/></Link><Link to="/infrastructure#power"><span>04</span><h3>All-electric baseline</h3><ArrowUpRight/></Link></div></section>
    <section className="section"><div className="section-heading"><div><p className="eyebrow">06 / A MEASURED PATH FORWARD</p><h2>Start with proof.<br />Build toward possibility.</h2></div><Link className="inline-link" to="/feasibility">Read the feasibility brief <ArrowUpRight size={18}/></Link></div><div className="roadmap">{gates.map(g => <article key={g.phase}><span className="phase">{g.phase}</span><span className="tag">{g.status}</span><h3>{g.title}</h3><p>{g.evidence}.</p></article>)}</div></section>
    <section className="commission section"><p className="eyebrow">FOR HOST CITIES, DEVELOPMENT PARTNERS & DESIGN TEAMS</p><h2>The next investment<br />is in the evidence.</h2><p>Rotunda is a proposal for a feasibility partnership. The immediate opportunity is to select a context, appoint a multidisciplinary team and test the mechanisms that would make the vision possible.</p><div className="hero-actions"><Link to="/feasibility" className="button primary">Review the project brief <ArrowUpRight size={18}/></Link><a className="button secondary" href="https://github.com/sagearbor/megaCity-rotating">Open project repository <ArrowUpRight size={18}/></a></div></section>
  </main>;
}
